---
apiVersion: v1
kind: Service
metadata:
  name: promtail-syslog-external
  namespace: monitoring
  annotations:
    io.cilium/lb-ipam-ips: "192.168.4.126"
spec:
  type: LoadBalancer
  ports:
    - name: syslog
      port: 514
      targetPort: 1514
      protocol: UDP
  selector:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: promtail
