apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls
  namespace: bitwarden
spec:
  secretName: bitwarden-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
  - bw.dlb.im
