apiVersion: v1
kind: Service
metadata:
  name: profilarr
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
  selector:
    app: profilarr
  ports:
  - name: http
    port: 6868
