apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-media
spec:
  capacity:
    storage: 100Ti
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - vers=3.0
  - uid=1000
  - gid=997
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-media-unique
    volumeAttributes:
      source: "//smb.local/media"
    nodeStageSecretRef:
      name: samba-creds
      namespace: media
