apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-vpn-gateway-ingress
  namespace: vpn-gateway
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - world
        - cluster
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
